### ISSUE TITLE
[PE-D][Tester B] CS2103T-F12-2-Invalid link in article.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#135]
Users may specify a link flag and input an invalid link. To replicate this:
`add -a h/The Great Article c/John Doe i/Jane Doe t/friends o/The Great Outlet d/10-10-2024 s/DRAFT l/test` will generate a article as shown below.

![Invalid link test in article.png](https://raw.githubusercontent.com/cyqjoseph/ped/main/files/087dd2b6-f49c-4124-8e6a-fb5bd3541c51.png)

Although the `link` tab is available for users to click on, clicking it will not do anything and this could be possibly misleading for the user. Maybe certain validation can be performed on the link field to prevent this!

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cyqjoseph/ped#6

**Comment by bennyLCK** [comment]
The problem can be split into 2 parts:
1) Allowing an invalid link to be added
2) Not providing a meaningful error message when link cannot work

We should address either one of the points mentioned in the DG under planned enhancements.
