### ISSUE TITLE
[PE-D][Tester E] Missing fields for edit documentation 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-2/tp#140]
Here it seems that the index should be provided (where I highlighted in the image). 

![image.png](https://raw.githubusercontent.com/willowisp01/ped/main/files/5357a7f6-582e-42a2-85a3-687471f18b1f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: willowisp01/ped#4

**Comment by Murugan-Maniish** [comment]
#153
