### ISSUE TITLE
[PE-D][Tester A] Sorting of contacts could be done automatically after edits and additions

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-2/tp#145]
I think it is better if sorting is done automatically after edits and additions instead of creating a function for users to call. Could allow users to toggle it off if they do not want the sorting functionality or on again if they change their minds.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ChuaZiLong/ped#4

**Comment by Murugan-Maniish** [comment]
Comment: Valid BUT more of a enhancement hence "Not In Scope"???

Action: Planned Enhancements in DG?
