### ISSUE TITLE
[PE-D][Tester A] Unintuitive ordering of article commands in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-2/tp#151]
The ordering of the commands in the UG is slightly odd as list articles comes before add articles, etc. It might be better to list them in the order that they are intended to be used to enhance readability.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ChuaZiLong/ped#6

**Comment by Murugan-Maniish** [comment]
True, reorder UG.
