### ISSUE TITLE
[PE-D][Tester C] Inconsistency in your filter -a command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#167]
![image.png](https://raw.githubusercontent.com/jasperng-nus/ped/main/files/fedda4e6-d691-4564-84fb-74d6708ff5cf.png)
this is my current article list

when I entered this command, filter -a s/test t/NUS st/ en/ 
it shows the John Doe Article, however I am unsure if your filter is suppose to match every single prefixes such as the status, tags, in between the start and end date or just any one will do
![image.png](https://raw.githubusercontent.com/jasperng-nus/ped/main/files/54a7d9c5-5a21-4327-9d39-ed74885f26ca.png)

because when i enter this command, filter -a s/DRAFT t/test st/ en/ 
it does not display any article, even though the status matches.
![image.png](https://raw.githubusercontent.com/jasperng-nus/ped/main/files/52899591-ee14-4811-b32c-ebd93ec6fdf9.png)

But this command, filter -a s/draft t/ st/ en/
is meant to restrict the display to showing only articles with draft status, 
it is the same as filter -a s/ t/NUS st/ en/
where it is meant to show only the tags and both command does show the article, so I assumed if we include more options like this filter -a s/test t/NUS st/ en/ 
the bound should be tighter and supposed to only look for status that has 'test' and tag containing 'NUS' and the start date and end date.

Could it be that for your filter -a command, TAG takes precedence? So unless the tag match it won't be displayed?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jasperng-nus/ped#3

**Comment by Ko-Khan** [comment]
Make sure in UG to clarify that only one filter command can be active!
