### ISSUE TITLE
[PE-D][Tester E] Missing / broken image in documentation at 3.2.10

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-2/tp#168]
The picture to the left of "opening link" is missing.

![image.png](https://raw.githubusercontent.com/willowisp01/ped/main/files/98d5df8c-6a46-4554-9d9d-6559d7216a24.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: willowisp01/ped#11

**Comment by Murugan-Maniish** [comment]
duplicate of #169
