### ISSUE TITLE
[PE-D][Tester E] Broken link in UG 3.2.10

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#169]
The link tries to take me to localhost:6149. I don't know what the intended purpose of the link is. 

![image.png](https://raw.githubusercontent.com/willowisp01/ped/main/files/5754e9be-3bcd-49d5-9dbf-e39eb17264e1.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: willowisp01/ped#12

**Comment by Murugan-Maniish** [comment]
is this a duplicate of #124
