### ISSUE TITLE
[PE-D][Tester D] Lack of clear all function for articles 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#180]
Description:
As there is a clear all function for persons, it would be expected to have a parallel `clear -a` function for articles. However, this is not implemented.

Steps to replicate:
NA

Severity:Low
Minor inconvenience for users as would need to manually one-by-one delete articles when wanting to clear all articles occasionally.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jyztintan/ped#18

**Comment by Murugan-Maniish** [comment]
Remove clear and update UG to reflect how to remove sample data to user
