### ISSUE TITLE
[PE-D][Tester D] Image in user guide not appearing

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-2/tp#181]
Description:
In the User Guide section 3.2.10, an image was not rendered.

![image.png](https://raw.githubusercontent.com/jyztintan/ped/main/files/e6cb6987-0dd4-4a4a-829a-4f8ed0296c10.png)

Severity: VeryLow
Cosmetic issue in documentation, that does not affect usage.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jyztintan/ped#19

**Comment by Murugan-Maniish** [comment]
#162
