### ISSUE TITLE
[PE-D][Tester D] Filter command takes in multiple inputs of same prefix

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#191]
Filter article command is able to accept multiple values for the same prefix when it should not. 

Steps to replicate:
1) Run `filter -a s/draft s/published t/ st/ en/` which should be an invalid command
2) Instead, it returns only published articles

![image.png](https://raw.githubusercontent.com/jyztintan/ped/main/files/f799c58c-d211-4f20-af9e-e39149692a52.png)

Severity:Low
Users may be confused as to what the list is filtered as it is not properly specified in this special case.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jyztintan/ped#28

**Comment by Ko-Khan** [comment]
won't fix as it involves upgrading feature
