### ISSUE TITLE
[PE-D][Tester D] No check for empty date input in articles

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#195]
Description:
Currently there is no check for empty date input in articles. As a result, empty dates receive invalid date error message when the more specific error is missing date input.

Steps to replicate:
1) `add -a h/ c/John Doe i/Jane Doe t/friends o/The Great Outlet d/ s/DRAFT l/https://www.example.com`

![image.png](https://raw.githubusercontent.com/jyztintan/ped/main/files/da375e03-be87-4777-9f33-7d2a1997a7d5.png)

Severity:Low
Unlikely to affect user workflow but could cause some inconvenience due to unchecked input validation.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jyztintan/ped#31

**Comment by H4mes** [comment]
Make forum post to clarify
