### ISSUE TITLE
[PE-D][Tester C] Handling of Duplicates for Article Title in Articles List

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#204]
![image.png](https://raw.githubusercontent.com/jasperng-nus/ped/main/files/7727d4ad-02f3-4947-b718-e3972ef91386.png)
Currently your app checks for duplicates by checking if the Article title existed already. However, I think that it is quite common for Article that might have the same title so perhaps your team could include checks for the date and maybe as well as the contributor or even the links to count it as a duplicate

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jasperng-nus/ped#14

**Comment by bennyLCK** [comment]
This is an expected behaviour that should be addressed in the UG under the add command description.
