### ISSUE TITLE
[PE-D][Tester B] CS2103T-F12-2-Long Headlines truncated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#207]
Upon entering a very long headline, the title details are truncated to fit the viewport. To replicate, `add -a h/The Great Article This is a very long message Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eu ipsum ut elit gravida laoreet non sed magna. Duis aliquet et lorem in vestibulum. Etiam sollicitudin hendrerit massa vitae pharetra. Vestibulum vel diam tempus, viverra ligula sed, elementum felis. eu.c/John Doe i/Jane Doe t/friends o/The Great Outlet d/10-10-2024 s/DRAFT l/https://www.example.com`

Below is the result of entering the command

![Screenshot 2024-04-05 at 9.57.21 PM.png](https://raw.githubusercontent.com/cyqjoseph/ped/main/files/623a1e9e-b4ea-4e72-bca1-31ecd3a1ee57.png)

An improvement could include having a character limit on headlines, or introduce some line breaks in headlines so we can accomodate more characters!

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: cyqjoseph/ped#17

**Comment by Murugan-Maniish** [comment]
Comment: Valid

Action: Fix to display full in Article list BUT argue we are not considering extreme inputs (basically that such long inputs is unlikely to be used by user).

**Comment by H4mes** [comment]
According to [Q8 of the FAQ](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html) truncating is ok, users can still see the full input by performing an edit -a command without making changes and scroll the message return, or resize the window.
