### ISSUE TITLE
[PE-D][Tester B] CS2103T-F12-2-Minor error in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-2/tp#209]
![Screenshot 2024-04-05 at 11.10.39 PM.png](https://raw.githubusercontent.com/cyqjoseph/ped/main/files/a1f7cccb-a3a6-4b36-b26e-f1a7b06f3e94.png)

From the above screenshot in 3.1.6 in the UG, `lookup` at the start indicates that the `INDEX` refers to the index number of the person in the address book, but later has the example that `lookup 1` returns all people with the **first** article in the list of article. 

This led to a bit of confusion as a user as i did not know what the command's true effect until i demo'ed it on the application.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: cyqjoseph/ped#18

**Comment by Murugan-Maniish** [comment]
Comment: Valid

Action: Update UG
